export const characterImages: Record<string, string> = {
  rashid: "rashid",
  juri: "juri",
  ken: "ken",
  luke: "luke",
  cammy: "cammy",
  guile: "guile",
  chunli: "chunli",
  blanka: "blanka",
  dhalsim: "dhalsim",
  manon: "manon",
  marisa: "marisa",
  mai: "mai",
  jp: "jp",
  akuma: "akuma",
  jamie: "jamie",
  deejay: "deejay",
  ed: "ed",
  honda: "honda",
  kimberly: "kimberly",
  zangief: "zangief",
  ryu: "ryu",
  // Additional characters from your image collection
  naruto: "naruto",
  itachi: "itachi",
  jotaro: "jotaro",
  yuyu: "yuyu",
  mario: "mario",
  terry: "terry",
  lily: "lily",
  elena: "elena",
  lamine: "lamine",
  mbison: "mbison",
  aki: "aki",
  sagat: "Sagat"
};

export const squareCardImages: Record<string, string> = {
  'ken': '/SquareCard_V2_TRANSPARENT/ken.png',
  'ryu': '/SquareCard_V2_TRANSPARENT/ryu.png',
  'luke': '/SquareCard_V2_TRANSPARENT/luke.png',
  'jamie': '/SquareCard_V2_TRANSPARENT/jamie.png',
  'ed': '/SquareCard_V2_TRANSPARENT/ed.png',
  'zangief': '/SquareCard_V2_TRANSPARENT/zangief.png',
  'akuma': '/SquareCard_V2_TRANSPARENT/akuma.png',
  'cammy': '/SquareCard_V2_TRANSPARENT/cammy.png',
  'chunli': '/SquareCard_V2_TRANSPARENT/chunli.png',
  'deejay': '/SquareCard_V2_TRANSPARENT/deejay.png',
  'dhalsim': '/SquareCard_V2_TRANSPARENT/dhalsim.png',
  'honda': '/SquareCard_V2_TRANSPARENT/honda.png',
  'guile': '/SquareCard_V2_TRANSPARENT/guile.png',
  'jp': '/SquareCard_V2_TRANSPARENT/jp.png',
  'juri': '/SquareCard_V2_TRANSPARENT/juri.png',
  'kimberly': '/SquareCard_V2_TRANSPARENT/kimberly.png',
  'lily': '/SquareCard_V2_TRANSPARENT/lily.png',
  'manon': '/SquareCard_V2_TRANSPARENT/manon.png',
  'marisa': '/SquareCard_V2_TRANSPARENT/marisa.png',
  'mbison': '/SquareCard_V2_TRANSPARENT/mbison.png',
  'mai': '/SquareCard_V2_TRANSPARENT/mai.png',
  'terry': '/SquareCard_V2_TRANSPARENT/terry.png',
  'elena': '/SquareCard_V2_TRANSPARENT/elena.png',
  'blanka': '/SquareCard_V2_TRANSPARENT/blanka.png',
  'rashid': '/SquareCard_V2_TRANSPARENT/rashid.png',
  'aki': '/SquareCard_V2_TRANSPARENT/aki.png',
  'sagat': '/SquareCard_V2_TRANSPARENT/Sagat.png'
}; 