export const characterImages = {
  rashid: "rashid",
  juri: "juri",
  ken: "ken",
  luke: "luke",
  cammy: "cammy",
  guile: "guile",
  chunli: "chunli",
  blanka: "blanka",
  dhalsim: "dhalsim",
  manon: "manon",
  marisa: "marisa",
  mai: "mai",
  jp: "jp",
  akuma: "akuma",
  jamie: "jamie",
  deejay: "deejay",
  ed: "ed",
  honda: "honda",
  kimberly: "kimberly",
  zangief: "zangief",
  ryu: "ryu",
  // Additional characters from your image collection
  naruto: "naruto",
  itachi: "itachi",
  jotaro: "jotaro",
  yuyu: "yuyu",
  mario: "mario",
  terry: "terry",
  lily: "lily",
  elena: "elena",
  lamine: "lamine",
  mbison: "mbison"
};
